name: Update Monday Status

on:
  pull_request:
    types:
      - closed

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "PR merged, updating Monday.com status"

      - name: Load environment variables
        run: |
          echo "MONDAY_API_KEY=${MONDAY_API_KEY}" >> $GITHUB_ENV
          echo "BOARD_ID=${BOARD_ID}" >> $GITHUB_ENV
          echo "ITEM_ID=${ITEM_ID}" >> $GITHUB_ENV
        env:
          MONDAY_TOKEN: $MONDAY_API_KEY
          BOARD_ID: $BOARD_ID
          ITEM_ID: $ITEM_ID

      - name: Set Monday Status
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            STATUS="Dev"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "test" ]]; then
            STATUS="Test"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            STATUS="Done"
          else
            echo "🚫 No status update needed"
            exit 0
          fi

          echo "🔄 Updating Monday.com status to '$STATUS'"

          curl -X POST "https://api.monday.com/v2" \
            -H "Authorization: $MONDAY_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation { change_simple_column_value (board_id: '"$BOARD_ID"', item_id: '"$ITEM_ID"', column_id: \"status\", value: \"'$STATUS'\") { id } }"
            }'
